version: 2

shared:
  node: &node
    docker:
      - image: cimg/node:16.16

  restore-yarn-cache: &restore-yarn-cache
    restore_cache:
      key: yarn-cache-{{ checksum "yarn.lock" }}

  build: &build
    steps:
      - checkout
      - *restore-yarn-cache
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules

  test: &test
    steps:
      - checkout
      - *restore-yarn-cache
      - run:
          name: Test
          command: yarn test

  lint: &lint
    steps:
      - checkout
      - *restore-yarn-cache
      - run:
          name: Test
          command: yarn lint

jobs:
  build-node:
    <<: *build
    <<: *node

  test-node:
    <<: *test
    <<: *node

  lint-node:
    <<: *lint
    <<: *node

workflows:
  version: 2
  pr:
    jobs:
      - build-node

      - lint-node:
          requires:
            - build-node

      - test-node:
          requires:
            - build-node
